services:
  - type: web
    name: antigravity-pos-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://zaheerhamza0_db_user:hamza1234@cluster0.zt64dhv.mongodb.net/antigravity_pos?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: antigravity_pos_jwt_super_secret_key_2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://frontend-hamza-s-projects-next.vercel.app
    healthCheckPath: /api/health
