services:
  - type: web
    name: antigravity-pos
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb://zaheerhamza0_db_user:hamza1234@ac-hwvtn5v-shard-00-00.zt64dhv.mongodb.net:27017,ac-hwvtn5v-shard-00-01.zt64dhv.mongodb.net:27017,ac-hwvtn5v-shard-00-02.zt64dhv.mongodb.net:27017/antigravity_pos?ssl=true&replicaSet=atlas-5g8tjr-shard-0&authSource=admin&retryWrites=true&w=majority
      - key: JWT_SECRET
        value: antigravity_pos_jwt_super_secret_key_2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://frontend-hamza-s-projects-next.vercel.app
    healthCheckPath: /api/health
